### ISSUE TITLE
Position and Control IO

### ISSUE THREAD

**Issue by Notgiven08** [qpit/thorlabs_apt#10]
Hello,

I am trying to implement python code for a NR360 with a BSC201.

I can move the motor. Although I am a bit confused where it actually moves to with certain commands. Which function returns the absolute position (if it was homed first)? I found in the APT Communications Protocol MGMSG_MOT_GET_POSCOUNTER. Is it possible this is not implemented in the code or are you using a different function for returning the position?

And I need to read out the Control IO. I can't seem to identify the appropriate functions for that either.

Any help would be greatly appreciated.
Thanks

**Comment by tobiasgehring** [comment]
MGMSG_MOT_GET_POSCOUNTER is a method from the ActiveX component and not available in APT.DLL.
