### ISSUE TITLE
ctypes issue - 'module' object has no attribute 'util'

### ISSUE THREAD

**Issue by cmoriarty** [qpit/thorlabs_apt#11]
I used pip to install thorlabs_apt, and I'm running python 2.7. 

Simply trying to run the import statement fails:
`import thorlabs_apt as apt`

```
filename = ctypes.util.find_library("APT")
AttributeError: 'module' object has no attribute 'util'
```

I was able to fix this by adding this line to core.py:
`from ctypes.util import find_library`

**Comment by Vieler** [comment]
I can confirm that this issues also affects a Python 3.6 installation. The fix was similar to @cmoriarty 's, I only added `import ctypes.util` at the top of `core.py`.

**Comment by ghost** [comment]
I found that if you use `from ctypes import util` instead of `from ctypes import *` or just `import ctypes`,  it works fine

**Comment by tobiasgehring** [comment]
since the github version uses import ctypes.util I assume this issue can be closed.
