### ISSUE TITLE
Works with Thorlabs NT100.

### ISSUE THREAD

**Issue by grkeiser** [qpit/thorlabs_apt#12]
Hi, just wanted to let you know this package works well to control the Thorlabs NT100 series stepper motor translation stages.  Maybe consider adding that to the list.  Sorry if this isn't the place to post such info.  I am not a regular github user.

This is the stage that I am working with:  https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=2131

**Comment by elevenert** [comment]
Hi grkeiser, I'm using two NT100 stages with BSC202. May I ask what controller did you use for your stage? Single channel BSC201? Also can you share the version of APT software you installed please?
