### ISSUE TITLE
StopImmediate Missing

### ISSUE THREAD

**Issue by cal-miller-harvard** [qpit/thorlabs_apt#20]
It would be desirable to access the StopImmediate function, in addition to StopProfiled. See excerpt from Thorlabs documentation below:

Motor Method StopImmediate 

See Also Example Code 

Visual Basic Syntax 

Function StopImmediate(lChanID As Long) As Long 

Parameters 

lChanID - the channel identifier 

Returns 

MG Return Code 

Details 

This method is called to stop motor moves on the channel specified by the lChanID parameter, which in turn takes values specified by the HWCHANNEL enumeration. 

Moves are stopped abruptly in a non-profiled manner, (i.e. the parameter fAccn, set using the SetVelParams method, is ignored) and there is a risk that steps, and therefore positional integrity, could be lost. 

This method can be called to stop prematurely, absolute or relative moves and, more importantly, is called to stop MoveAtVelocity moves.

**Comment by tobiasgehring** [comment]
Unfortunately StopImmediate only exists in the ActiveX, not in apt.dll. This wrapper is based on the latter so this cannot be fixed.
